### ISSUE TITLE
Main included in shared library?

### ISSUE THREAD

**Issue by allsey87** [demiurge-project/argos3-epuck#12]
Looking at the cmake, it seems that the main function from real_robot/real_epuck_main.cpp ends up in one of the main shared libraries. Is this intentional?

See:
1. https://github.com/demiurge-project/argos3-epuck/blob/master/src/plugins/robots/e-puck/RealLibrary.cmake#L52
2. https://github.com/demiurge-project/argos3-epuck/blob/master/src/plugins/robots/e-puck/RealLibrary.cmake#L58
3. https://github.com/demiurge-project/argos3-epuck/blob/master/src/plugins/robots/e-puck/RealLibrary.cmake#L89

**Comment by KenN7** [comment]
I'm updating the lib for the argos3-beta56, i'm taking the opportunity to also fix this minor issue.
thx for pointing it out. Fixed by bb79e6e9c03c2d42a2bd224a5a84379ea1e2a947
